-- MySQL Script generated by MySQL Workbench
-- Wed May  1 17:19:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema illnesses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema illnesses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `illnesses` DEFAULT CHARACTER SET utf8 ;
USE `illnesses` ;

-- -----------------------------------------------------
-- Table `illnesses`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `illnesses`.`sintomas` (
  `idsintomas` INT NOT NULL AUTO_INCREMENT,
  `nombsintoma` VARCHAR(250) NULL,
  `imgsintoma` VARCHAR(250) NULL,
  PRIMARY KEY (`idsintomas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `illnesses`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `illnesses`.`tratamientos` (
  `idtratamientos` INT NOT NULL AUTO_INCREMENT,
  `nombtrat` VARCHAR(250) NULL,
  PRIMARY KEY (`idtratamientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `illnesses`.`enfermedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `illnesses`.`enfermedades` (
  `idenfermedades` INT NOT NULL AUTO_INCREMENT,
  `nombenf` VARCHAR(250) NULL,
  `imgenf` VARCHAR(250) NULL,
  `tratamientos_idtratamientos` INT NOT NULL,
  PRIMARY KEY (`idenfermedades`),
  CONSTRAINT `fk_enfermedades_tratamientos1`
    FOREIGN KEY (`tratamientos_idtratamientos`)
    REFERENCES `illnesses`.`tratamientos` (`idtratamientos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `illnesses`.`enfermedades_has_sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `illnesses`.`enfermedades_has_sintomas` (
  `id_enf-sint` INT NOT NULL AUTO_INCREMENT,
  `sintomas_idsintomas` INT NOT NULL,
  `enfermedades_idenfermedades` INT NOT NULL,
  `valor` DECIMAL (10,2) NULL,
  PRIMARY KEY (`id_enf-sint`),
  CONSTRAINT `fk_sintomas_has_enfermedades_sintomas`
    FOREIGN KEY (`sintomas_idsintomas`)
    REFERENCES `illnesses`.`sintomas` (`idsintomas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sintomas_has_enfermedades_enfermedades1`
    FOREIGN KEY (`enfermedades_idenfermedades`)
    REFERENCES `illnesses`.`enfermedades` (`idenfermedades`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
